name = "testing-deploy"
type = "javascript"
account_id = "97745ed61bad1988fa5b6b2072ede438"
compatibility_date = "2025-05-23"

main = "src/index.js" 

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "testing-deploy"
preview_bucket_name = "testing-deploy"
